[package]
name = "vega68"
version = "0.1.0"
edition.workspace = true
license.workspace = true
default-run = "vega68"

[[bin]]
name = "vega68"
path = "src/main.rs"

[dependencies]
sdl3-sys = { version = "0.6", features = ["build-from-source-static"] }

[dev-dependencies]
xtask = { path = "../xtask" }

[build-dependencies]
cc = "1"
